version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # 如果需要暴露端口
    environment:
      - PYTHONPATH=/app
    tty: true
    stdin_open: true 